on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Escolha o ambiente que melhor se adequa (ubuntu-latest, windows-latest, etc.)

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          maven-version: '4.0.0'

      - name: Install dependencies
        run: mvn clean install  # ou ./mvnw install se usar o wrapper do Maven

      - name: Run tests with headless Chrome
        run: mvn test -Dcucumber.options="--tags @smoke" -Dwebdriver.chrome.driver="/usr/bin/chromedriver"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/cucumber-reports  # Caminho onde os resultados dos testes Cucumber são armazenados
